// Code generated by MockGen. DO NOT EDIT.
// Source: subject.go

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/student-api/models"
)

// MocksubjectHandler is a mock of subjectHandler interface.
type MocksubjectHandler struct {
	ctrl     *gomock.Controller
	recorder *MocksubjectHandlerMockRecorder
}

// MocksubjectHandlerMockRecorder is the mock recorder for MocksubjectHandler.
type MocksubjectHandlerMockRecorder struct {
	mock *MocksubjectHandler
}

// NewMocksubjectHandler creates a new mock instance.
func NewMocksubjectHandler(ctrl *gomock.Controller) *MocksubjectHandler {
	mock := &MocksubjectHandler{ctrl: ctrl}
	mock.recorder = &MocksubjectHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubjectHandler) EXPECT() *MocksubjectHandlerMockRecorder {
	return m.recorder
}

// GetValidation mocks base method.
func (m *MocksubjectHandler) GetValidation(id int) (models.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidation", id)
	ret0, _ := ret[0].(models.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidation indicates an expected call of GetValidation.
func (mr *MocksubjectHandlerMockRecorder) GetValidation(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidation", reflect.TypeOf((*MocksubjectHandler)(nil).GetValidation), id)
}

// InsertValidation mocks base method.
func (m *MocksubjectHandler) InsertValidation(sub models.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertValidation", sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertValidation indicates an expected call of InsertValidation.
func (mr *MocksubjectHandlerMockRecorder) InsertValidation(sub interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertValidation", reflect.TypeOf((*MocksubjectHandler)(nil).InsertValidation), sub)
}
